# Generated by Django 4.0.1 on 2022-02-25 03:06

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('budget', '0003_remove_transaction_builtin_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 25, 3, 6, 23, 923380)),
        ),
        migrations.CreateModel(
            name='Spendable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datestart', models.DateTimeField(default=datetime.datetime(2022, 2, 25, 3, 6, 23, 921286))),
                ('dateend', models.DateTimeField(blank=True, null=True)),
                ('current', models.BooleanField(blank=True, default=False, null=True)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Dailyresult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tospend', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('spent', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('leftover', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('status', models.CharField(blank=True, max_length=200, null=True)),
                ('date', models.DateTimeField()),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
