# Generated by Django 4.0.1 on 2022-02-25 04:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0005_spendable_dispincome_alter_spendable_datestart_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyresult',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='spendable',
            name='datestart',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 25, 4, 28, 16, 688458)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 25, 4, 28, 16, 691495)),
        ),
    ]
