# Generated by Django 4.0.1 on 2022-02-25 04:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0006_dailyresult_budget_alter_spendable_datestart_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyresult',
            name='tospend',
        ),
        migrations.AlterField(
            model_name='spendable',
            name='datestart',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 25, 4, 29, 34, 803467)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 25, 4, 29, 34, 806462)),
        ),
    ]
