# Generated by Django 4.0.1 on 2022-02-25 04:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0007_remove_dailyresult_tospend_alter_spendable_datestart_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyresult',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='spendable',
            name='dateend',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='spendable',
            name='datestart',
            field=models.DateField(default=datetime.datetime(2022, 2, 25, 4, 41, 7, 154831)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 25, 4, 41, 7, 160148)),
        ),
    ]
