# Generated by Django 4.0.1 on 2022-02-25 04:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0008_alter_dailyresult_date_alter_spendable_dateend_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spendable',
            name='dateend',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='spendable',
            name='datestart',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 25, 4, 42, 42, 545847)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 25, 4, 42, 42, 548800)),
        ),
    ]
