# Generated by Django 4.0.1 on 2022-02-25 04:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0010_alter_spendable_dateend_alter_spendable_datestart_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spendable',
            name='datestart',
            field=models.DateField(default=datetime.datetime(2022, 2, 25, 4, 45, 22, 207882)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 2, 25, 4, 45, 22, 210935)),
        ),
    ]
