# Generated by Django 4.0.1 on 2022-02-25 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0011_alter_spendable_datestart_alter_transaction_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spendable',
            name='datestart',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(),
        ),
    ]
